name: CI

on:
  push:
    branches:
      - buildroot

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - name: Install packages
        run: |
          export DEBIAN_FRONTEND=noninteractive
          dpkg --add-architecture i386
          apt-get update -y
          apt-get install -y --no-install-recommends \
                  bc \
                  build-essential \
                  bzr \
                  ca-certificates \
                  cmake \
                  cpio \
                  cvs \
                  file \
                  g++-multilib \
                  git \
                  libc6:i386 \
                  libncurses5-dev \
                  locales \
                  mercurial \
                  python3 \
                  python3-flake8 \
                  python3-nose2 \
                  python3-pexpect \
                  qemu-system-arm \
                  qemu-system-x86 \
                  rsync \
                  subversion \
                  unzip \
                  wget 
          apt-get -y autoremove
          apt-get -y clean

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache buildroot-ccache
        id: buildroot-ccache
        uses: actions/cache@v2
        with:
          path: ~/.buildroot-ccache
          key: buildroot-ccache-${{ hashFiles('.git/modules/images/buildroot/HEAD', 'images/custom/configs/*', 'images/custom/support/configs-fragments/**') }}
          restore-keys: |
            buildroot-ccache-
      - name: Cache buildroot-dl
        id: buildroot-dl
        uses: actions/cache@v2
        with:
          path: images/buildroot/dl
          key: buildroot-dl-${{ hashFiles('.git/modules/images/buildroot/HEAD', 'images/custom/configs/*', 'images/custom/support/configs-fragments/**') }}
          restore-keys: |
            buildroot-dl-

      - name: Setup locales
        run: |
          sed -i 's/# \(en_US.UTF-8\)/\1/' /etc/locale.gen
          /usr/sbin/locale-gen

      - name: Build
        run: |
          export LC_ALL=en_US.UTF-8
          export FORCE_UNSAFE_CONFIGURE=1
          cd images
          make -j4

      - uses: actions/upload-artifact@v2
        with:
          name: rpi-images
          path: images/build/raspberrypi/images/*.img 
